# Generated by Django 5.2.9 on 2026-02-03 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('longclaw_shipping', '0001_initial'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_shipping_rate', models.DecimalField(decimal_places=2, default=3.95, help_text='The default shipping rate for countries which have not been configured', max_digits=12)),
                ('default_shipping_carrier', models.CharField(default='Royal Mail', help_text='The default shipping carrier', max_length=32)),
                ('default_shipping_enabled', models.BooleanField(default=False, help_text='Whether to enable default shipping. This essentially means you ship to all countries, not only those with configured shipping rates')),
                ('currency_html_code', models.CharField(default='&pound;', help_text='The HTML code for the currency symbol. Used for display purposes only', max_length=12)),
                ('currency', models.CharField(default='GBP', help_text='The iso currency code to use for payments', max_length=6)),
                ('shipping_origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='longclaw_shipping.address')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Shop Configuration',
            },
        ),
    ]
