# Generated by Django 5.2.9 on 2026-06-12 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('longclaw_shipping', '0003_alter_address_options_alter_country_options_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_shipping_rate', models.DecimalField(decimal_places=2, default=3.95, help_text='The default shipping rate for countries which have not been configured', max_digits=12, verbose_name='Default shipping rate')),
                ('default_shipping_carrier', models.CharField(default='Royal Mail', help_text='The default shipping carrier', max_length=32, verbose_name='Default shipping carrier')),
                ('default_shipping_enabled', models.BooleanField(default=False, help_text='Whether to enable default shipping. This essentially means you ship to all countries, not only those with configured shipping rates', verbose_name='Default shipping enabled')),
                ('currency_html_code', models.CharField(default='&pound;', help_text='The HTML code for the currency symbol. Used for display purposes only', max_length=12, verbose_name='Currency HTML code')),
                ('currency', models.CharField(default='GBP', help_text='The iso currency code to use for payments', max_length=6, verbose_name='Currency')),
                ('enable_automatic_stock', models.BooleanField(default=True, help_text='If this is enabled, the products stock will automatically be updated when an order is placed.', verbose_name='Enable automatic stock')),
                ('shipping_origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='longclaw_shipping.address', verbose_name='Shipping origin')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Shop Configuration',
            },
        ),
    ]
