# Generated by Django 5.2.9 on 2026-05-31 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('longclaw_configuration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='enable_automatic_stock',
            field=models.BooleanField(default=True, help_text='If this is enabled, the products stock will automatically be updated when an order is placed.'),
        ),
    ]
