# Generated by Django 5.2.9 on 2026-06-08 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('longclaw_configuration', '0002_configuration_enable_automatic_stock'),
        ('longclaw_shipping', '0003_alter_address_options_alter_country_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='currency',
            field=models.CharField(default='GBP', help_text='The iso currency code to use for payments', max_length=6, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='currency_html_code',
            field=models.CharField(default='&pound;', help_text='The HTML code for the currency symbol. Used for display purposes only', max_length=12, verbose_name='Currency HTML code'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='default_shipping_carrier',
            field=models.CharField(default='Royal Mail', help_text='The default shipping carrier', max_length=32, verbose_name='Default shipping carrier'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='default_shipping_enabled',
            field=models.BooleanField(default=False, help_text='Whether to enable default shipping. This essentially means you ship to all countries, not only those with configured shipping rates', verbose_name='Default shipping enabled'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='default_shipping_rate',
            field=models.DecimalField(decimal_places=2, default=3.95, help_text='The default shipping rate for countries which have not been configured', max_digits=12, verbose_name='Default shipping rate'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='enable_automatic_stock',
            field=models.BooleanField(default=True, help_text='If this is enabled, the products stock will automatically be updated when an order is placed.', verbose_name='Enable automatic stock'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='shipping_origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='longclaw_shipping.address', verbose_name='Shipping origin'),
        ),
    ]
