# Generated by Django 5.2.9 on 2026-02-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(blank=True, help_text='Optional email of the customer who made the request', max_length=254, null=True)),
            ],
        ),
    ]
