# Generated by Django 5.2.9 on 2026-06-08 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('longclaw_productrequests', '0002_initial'),
        migrations.swappable_dependency(settings.PRODUCT_VARIANT_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productrequest',
            options={'verbose_name': 'Product Request', 'verbose_name_plural': 'Product Requests'},
        ),
        migrations.AlterField(
            model_name='productrequest',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='productrequest',
            name='email',
            field=models.EmailField(blank=True, help_text='Optional email of the customer who made the request', max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='productrequest',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.PRODUCT_VARIANT_MODEL, verbose_name='Variant'),
        ),
    ]
