# Generated by Django 5.2.9 on 2026-07-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('longclaw_productrequests', '0003_alter_productrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
