# Generated by Django 5.2.9 on 2026-02-02 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('longclaw_basket', '0001_initial'),
        migrations.swappable_dependency(settings.PRODUCT_VARIANT_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='basketitem',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.PRODUCT_VARIANT_MODEL),
        ),
    ]
