# Generated by Django 5.2.9 on 2026-07-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('longclaw_basket', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
