# Generated by Django 5.2.9 on 2026-06-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testproducts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'verbose_name': 'Product Variant', 'verbose_name_plural': 'Product Variants'},
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Base price'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='ref',
            field=models.CharField(max_length=32, verbose_name='Reference'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock'),
        ),
    ]
