# Generated by Django 5.2.9 on 2026-06-08 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('longclaw_shipping', '0002_alter_country_options_remove_country_sort_priority_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='shippingrate',
            options={'verbose_name': 'Shipping Rate', 'verbose_name_plural': 'Shipping Rates'},
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=64, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='longclaw_shipping.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='address',
            name='line_1',
            field=models.CharField(max_length=128, verbose_name='Line 1'),
        ),
        migrations.AlterField(
            model_name='address',
            name='line_2',
            field=models.CharField(blank=True, max_length=128, verbose_name='Line 2'),
        ),
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postcode',
            field=models.CharField(max_length=10, verbose_name='Postcode'),
        ),
        migrations.AlterField(
            model_name='country',
            name='iso',
            field=models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='ISO'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Name of Country'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name_official',
            field=models.CharField(max_length=128, verbose_name='Name of Official'),
        ),
        migrations.AlterField(
            model_name='shippingrate',
            name='basket_id',
            field=models.CharField(blank=True, db_index=True, max_length=32, verbose_name='Basket ID'),
        ),
        migrations.AlterField(
            model_name='shippingrate',
            name='carrier',
            field=models.CharField(max_length=64, verbose_name='Carrier'),
        ),
        migrations.AlterField(
            model_name='shippingrate',
            name='countries',
            field=models.ManyToManyField(to='longclaw_shipping.country', verbose_name='Countries'),
        ),
        migrations.AlterField(
            model_name='shippingrate',
            name='description',
            field=models.CharField(max_length=128, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='shippingrate',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='longclaw_shipping.address', verbose_name='Destination'),
        ),
        migrations.AlterField(
            model_name='shippingrate',
            name='name',
            field=models.CharField(help_text='Unique name to refer to this shipping rate by', max_length=32, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='shippingrate',
            name='processor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='longclaw_shipping.shippingrateprocessor', verbose_name='Processor'),
        ),
        migrations.AlterField(
            model_name='shippingrate',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Rate'),
        ),
        migrations.AlterField(
            model_name='shippingrateprocessor',
            name='countries',
            field=models.ManyToManyField(to='longclaw_shipping.country', verbose_name='Countries'),
        ),
    ]
