# Generated by Django 5.2.9 on 2026-06-12 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('longclaw_shipping', '0003_alter_address_options_alter_country_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrivialShippingRateProcessor',
            fields=[
                ('shippingrateprocessor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='longclaw_shipping.shippingrateprocessor')),
            ],
            options={
                'abstract': False,
            },
            bases=('longclaw_shipping.shippingrateprocessor',),
        ),
    ]
