# Generated by Django 5.2.9 on 2026-02-28 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('longclaw_orders', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('fulfill_order', 'Can fulfill orders'), ('cancel_order', 'Can cancel orders'), ('refund_order', 'Can refund orders')]},
        ),
    ]
