# Generated by Django 5.2.9 on 2026-05-31 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('longclaw_orders', '0004_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stock_updated',
            field=models.BooleanField(default=False),
        ),
    ]
