# Generated by Django 5.2.9 on 2026-06-08 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('longclaw_orders', '0005_order_stock_updated'),
        ('longclaw_shipping', '0003_alter_address_options_alter_country_options_and_more'),
        migrations.swappable_dependency(settings.PRODUCT_VARIANT_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('fulfill_order', 'Can fulfill orders'), ('cancel_order', 'Can cancel orders'), ('refund_order', 'Can refund orders')], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Order Item', 'verbose_name_plural': 'Order Items'},
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders_billing_address', to='longclaw_shipping.address', verbose_name='Billing address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=128, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Payment date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders_shipping_address', to='longclaw_shipping.address', verbose_name='Shipping address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Shipping rate'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Submitted'), (2, 'Fulfilled'), (3, 'Cancelled'), (4, 'Refunded'), (5, 'Payment Failed')], default=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status_note',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Status note'),
        ),
        migrations.AlterField(
            model_name='order',
            name='stock_updated',
            field=models.BooleanField(default=False, verbose_name='Stock updated'),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Transaction ID'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='longclaw_orders.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.PRODUCT_VARIANT_MODEL, verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Quantity'),
        ),
    ]
