# Generated by Django 5.2.9 on 2026-07-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('longclaw_orders', '0007_order_customer_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='basket_id',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
